projeto/apps/perfil/urls.py
from django.urls import path
from .views import Show

app_name = 'perfil'

urlpatterns = [
    path('',Show.as_view(),name='show'),
]

projeto/apps/search/urls.py
from django.urls import path
from .views import ListUsers

app_name = 'search'

urlpatterns = [
    path('',ListUsers.as_view(),name='list.users'),
]

projeto/tattobook/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from apps.pages.views import IndexView
from apps.users.views import LoginView,RegisterView

urlpatterns = [
    path('',IndexView.as_view(),name='index'),
    path('login',LoginView.as_view(),name='login'),
    path('register',RegisterView.as_view(),name='register'),
    path('admin/', admin.site.urls),
    path('feed/',include('apps.feed.urls')),
    path('users/',include('apps.users.urls')),
    path('chat/',include('apps.chat.urls')),
    path('search/',include('apps.search.urls')),
    path('post/',include('apps.post.urls')),
    path('gerenciar/',include('apps.gerenciar_perfil.urls')),
    path('<str:username>/',include('apps.perfil.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto/apps/search/models.py
from django.db import models

# Create your models here.

projeto/apps/search/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect, get_object_or_404
from django.views import generic
from apps.users.models import CustomUser
from django.http import JsonResponse,HttpRequest
from django.contrib.auth.mixins import LoginRequiredMixin

class ListUsers(LoginRequiredMixin,generic.TemplateView):
    template_name = 'search/templates/list-users.html'
    def get(self,request):
        query = request.GET.get('q')
        if query:
            tatuadores = CustomUser.objects.filter(username__icontains=query,user_type=1)
        else:
            tatuadores = CustomUser.objects.filter(user_type=1).order_by('username')
        context = {
            'tatuadores':tatuadores,
        }
        if(HttpRequest.is_ajax(request)):
            all_users = []
            if(len(tatuadores)>0):
                for tatuador in tatuadores:
                    avatar = tatuador.setting.avatar.url if tatuador.setting.avatar else None
                    all_users.append({
                        'username':tatuador.username,
                        'name':tatuador.name,
                        'avatar':avatar
                    })
            return JsonResponse({'tatuadores':all_users},status=200)
        else:
            return render(request,self.template_name,context)

projeto/templates/search/components/result-bar.html
<div class="result-bar">
{#    <a href="#"> Tags </a>#}
    <a href="#" class="selected"> Tatuadores </a>
</div>

projeto/templates/search/components/users-list.html
<div class="users-list">
    {% for tatuador in tatuadores %}
        <div class="user">
            {% if tatuador.setting.avatar.url is not null %}
                <a class="avatar" href="{% url 'perfil:show' tatuador.username %}" style="background-image: url({{ tatuador.setting.avatar.url }})"></a>
            {% else %}
                <a class="avatar empty-avatar" href="{% url 'perfil:show' tatuador.username %}" ></a>
            {% endif %}
            <div class="informations">
                <a class="name" href="{% url 'perfil:show' tatuador.username %}">{{ tatuador.name }}</a>
                <span class="location">Natal, Rio Grande do Norte</span>
            </div>
{#            <i class="far fa-heart" data-action="follow-user"></i>#}
        </div>
    {% endfor %}
</div>

projeto/templates/search/components/users-pre-search.html
<div class="users-pre-search none" id="pre-search-div">
    <div class="users" id="pre-search-users">
    </div>
    <span class="query-search"><span id="search-span">BUSCA:</span><span id="query-search"></span></span>
</div>